### ISSUE TITLE
Question regarding use of feature extractors with these environments

### ISSUE THREAD

**Issue by BenSturgeon** [ini/multigrid#1]
Hey there

I am hoping to use this repo for some experiments in RL, but I have had some real troubles with processing observations from the environment.

I've been trying to use a modified version of the minigrid feature extractor https://minigrid.farama.org/content/training/#train-a-ppo-agent as described here, but I haven't been able to get the right dimensions of the outputs because of the different structure of observations of the environment.

My question is whether use of such a feature extractor is necessary with these environments, and if so what is a good strategy for implementing one?

I don't want to use the stable-baselines algorithms, since I want to implement a custom reward function and specifically extract the policies from the networks for other purposes.

Any advice would be much appreciated.

**Comment by ini** [comment]
Hi,

Not sure if you've been able to work out your particular use case, but as of commit 0e39624, you should be able to train homogeneous agents [using the same minigrid feature extractor](https://minigrid.farama.org/content/training/#create-custom-feature-extractor) with PettingZoo + SuperSuit + Stable Baselines 3 as follows:

```
import multigrid.envs
from multigrid.pettingzoo import PettingZooWrapper
from multigrid.wrappers import ImgObsWrapper

env = gym.make('MultiGrid-Empty-8x8-v0', agents=2)
env = ImgObsWrapper(env)
env = PettingZooWrapper(env)
env = supersuit.pettingzoo_env_to_vec_env_v1(env)
env = supersuit.concat_vec_envs_v1(env, 8, base_class='stable_baselines3')

policy_kwargs = dict(
    features_extractor_class= MinigridFeaturesExtractor,
    features_extractor_kwargs=dict(features_dim=128),
)

model = PPO("CnnPolicy", env, policy_kwargs=policy_kwargs, verbose=1)
model.learn(2e5)
```

However, stable_baselines is not exactly designed for multi-agent environments, so I would recommend using a different RL library with multi-agent support (e.g. [RLlib](https://docs.ray.io/en/latest/rllib/index.html), which we provide [example scripts](https://github.com/ini/multigrid/tree/master/scripts) for).
