### ISSUE TITLE
Error while trainning

### ISSUE THREAD

**Issue by marques576** [ini/multigrid#2]
```
def model_config(lstm: bool = False, **model_kwargs) -> dict[str, Any]:
    """
    Return a model configuration dictionary for RLlib.

    Parameters
    ----------
    lstm : bool
        Whether to use an LSTM model
    """
    return {
        'custom_model': CustomLSTMModel if lstm else CustomModel,
        'custom_model_config': model_kwargs,
        'conv_filters': [
            [16, [3, 3], 1],
            [16, [1, 1], 1],
            [32, [3, 3], 1],
            [32, [1, 1], 1],
            [64, [3, 3], 1],
            [64, [1, 1], 1],
        ],
        'fcnet_hiddens': [64, 64],
        'fcnet_activation': 'tanh',
        'post_fcnet_hiddens': [],
        'lstm_cell_size': 64,
        'max_seq_len': 8,
    }

def algorithm_config(
    algo: str = 'PPO',
    env: str = 'MultiGrid-Empty-8x8-v0',
    env_config: dict = {},
    num_agents: int = 2,
    lstm: bool = False,
    num_workers: int = 0,
    num_gpus: int = 0,
    lr: float | None = None,
    centralized_critic: bool = False,
    **kwargs) -> AlgorithmConfig:
    """
    Return the RL algorithm configuration dictionary.
    """
    _, env_creator = Algorithm._get_env_id_and_creator(env, {})
    env_config = {**env_config, 'agents': num_agents}
    dummy_env = env_creator(env_config)
    value_input_space = get_critic_input_space(dummy_env) if centralized_critic else None

    config = (
        get_trainable_cls(algo)
        .get_default_config()
        .debugging(seed=random.randint(0, int(1e6)))
        .environment(env=env, env_config=env_config)
        .framework('torch')
        .multi_agent(
            policies={f'policy_{i}' for i in range(num_agents)},
            policy_mapping_fn=get_policy_mapping_fn(None, num_agents),
        )
        .resources(num_gpus=num_gpus if torch.cuda.is_available() else 0)
        #.rl_module(_enable_rl_module_api=False) # disable RLModule API
        .experimental(_enable_new_api_stack=False)
        .rollouts(num_rollout_workers=num_workers)
        .training(
            #_enable_learner_api=False, # disable RLModule API
            model=model_config(lstm=lstm, value_input_space=value_input_space),
            lr=(lr or NotProvided),
        )
    )

    if centralized_critic:
        config = config.callbacks(CentralizedCriticCallbacks)

    return config

def train(
    algo: str,
    config: AlgorithmConfig,
    stop_conditions: dict,
    save_dir: str,
    load_dir: str | None = None):
    """
    Train an RLlib algorithm.
    """
    ray.init(num_cpus=min(os.cpu_count(), config.num_rollout_workers + 1),num_gpus=config.num_gpus)
    tune.run(
        algo,
        stop=stop_conditions,
        config=config,
        local_dir=save_dir,
        verbose=1,
        restore=find_checkpoint_dir(load_dir),
        checkpoint_freq=20,
        checkpoint_at_end=True,
    )
    ray.shutdown()



if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument(
        '--algo', type=str, default='PPO',
        help="The name of the RLlib-registered algorithm to use.")
    parser.add_argument(
        '--env', type=str, default='MultiGrid-Empty-8x8-v0',
        help="MultiGrid environment to use.")
    parser.add_argument(
        '--env-config', type=json.loads, default={},
        help="Environment config dict, given as a JSON string (e.g. '{\"size\": 8}')")
    parser.add_argument(
        '--num-agents', type=int, default=2,
        help="Number of agents in environment.")
    parser.add_argument(
        '--lstm', action='store_true',
        help="Use LSTM model.")
    parser.add_argument(
        '--centralized-critic', action='store_true',
        help="Use centralized critic for training.")
    parser.add_argument(
        '--num-workers', type=int, default=8,
        help="Number of rollout workers.")
    parser.add_argument(
        '--num-gpus', type=int, default=1,
        help="Number of GPUs to train on.")
    parser.add_argument(
        '--num-timesteps', type=int, default=1e7,
        help="Total number of timesteps to train.")
    parser.add_argument(
        '--lr', type=float,
        help="Learning rate for training.")
    parser.add_argument(
        '--load-dir', type=str,
        help="Checkpoint directory for loading pre-trained policies.")
    parser.add_argument(
        '--save-dir', type=str, default='~/ray_results/',
        help="Directory for saving checkpoints, results, and trained policies.")

    args = parser.parse_args()
    config = algorithm_config(**vars(args))

    print()
    print(f"Running with following CLI options: {args}")
    print('\n', '-' * 64, '\n', "Training with following configuration:", '\n', '-' * 64)
    print()

    stop_conditions = {'timesteps_total': args.num_timesteps}
    train(args.algo, config, stop_conditions, args.save_dir, args.load_dir)
```

__I get this error__
(PPO pid=213402)  (:::) ray/rllib/algorithms/ppo/ppo_torch_policy.py", line 141, in loss
(PPO pid=213402)     value_fn_out - train_batch[Postprocessing.VALUE_TARGETS], 2.0
(PPO pid=213402)     ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
(PPO pid=213402) RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by ini** [comment]
Which version of Ray / RLlib are you using?

**Comment by Tanujk23** [comment]
even i am facing the same error as above.
Ray version is 2.9.2

**Comment by ini** [comment]
Should be fixed now with commit 56a08fde2f2a2db800ff51ab19e9efd2cb54a393.

**Comment by Tanujk23** [comment]
also facing a similar error in visualize.py, that might also be due to the ray version 
please have a look.

**Comment by Tanujk23** [comment]
getting similar type of issue while running visualize.py
Ray version 2.9.2

(multigrid) [karuturi.t@c0900a-s29 scripts]$ python visualize.py --algo PPO --env MultiGrid-Empty-5x5-v0 --num-agents 2 --load-dir ~/blue_fujie/karuturi.t/MAgrid_repos/multigrid/scripts/saved/empty8x8/ --gif ~/blue_fujie/karuturi.t/MAgrid_repos/multigrid/scripts/saved/gif/
/home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/gymnasium/spaces/box.py:130: UserWarning: WARN: Box bound precision lowered by casting to float32
  gym.logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
/home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/gymnasium/utils/passive_env_checker.py:164: UserWarning: WARN: The obs returned by the `reset()` method was expecting numpy array dtype to be float32, actual type: float64
  logger.warn(
/home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/gymnasium/utils/passive_env_checker.py:188: UserWarning: WARN: The obs returned by the `reset()` method is not within the observation space.
  logger.warn(f"{pre} is not within the observation space.")
/home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py:483: RayDeprecationWarning: This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS="ignore::DeprecationWarning"
`UnifiedLogger` will be removed in Ray 2.7.
  return UnifiedLogger(config, logdir, loggers=None)
/home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/ray/tune/logger/unified.py:53: RayDeprecationWarning: This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS="ignore::DeprecationWarning"
The `JsonLogger interface is deprecated in favor of the `ray.tune.json.JsonLoggerCallback` interface and will be removed in Ray 2.7.
  self._loggers.append(cls(self.config, self.logdir, self.trial))
/home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/ray/tune/logger/unified.py:53: RayDeprecationWarning: This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS="ignore::DeprecationWarning"
The `CSVLogger interface is deprecated in favor of the `ray.tune.csv.CSVLoggerCallback` interface and will be removed in Ray 2.7.
  self._loggers.append(cls(self.config, self.logdir, self.trial))
/home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/ray/tune/logger/unified.py:53: RayDeprecationWarning: This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS="ignore::DeprecationWarning"
The `TBXLogger interface is deprecated in favor of the `ray.tune.tensorboardx.TBXLoggerCallback` interface and will be removed in Ray 2.7.
  self._loggers.append(cls(self.config, self.logdir, self.trial))
Traceback (most recent call last):
  File "/blue/fujie/karuturi.t/MAgrid_repos/multigrid/scripts/visualize.py", line 137, in <module>
    algorithm = config.build()
  File "/home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm_config.py", line 1137, in build
    return algo_class(
  File "/home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 516, in __init__
    super().__init__(
  File "/home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 161, in __init__
    self.setup(copy.deepcopy(self.config))
  File "/home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 638, in setup
    self.workers = WorkerSet(
  File "/home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/ray/rllib/evaluation/worker_set.py", line 159, in __init__
    self._setup(
  File "/home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/ray/rllib/evaluation/worker_set.py", line 249, in _setup
    self._local_worker = self._make_worker(
  File "/home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/ray/rllib/evaluation/worker_set.py", line 950, in _make_worker
    worker = cls(
  File "/home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/ray/rllib/evaluation/rollout_worker.py", line 535, in __init__
    self._update_policy_map(policy_dict=self.policy_dict)
  File "/home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1746, in _update_policy_map
    self._build_policy_map(
  File "/home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1857, in _build_policy_map
    new_policy = create_policy_for_framework(
  File "/home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/ray/rllib/utils/policy.py", line 141, in create_policy_for_framework
    return policy_class(observation_space, action_space, merged_config)
  File "/home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/ray/rllib/algorithms/ppo/ppo_torch_policy.py", line 64, in __init__
    self._initialize_loss_from_dummy_batch()
  File "/home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/ray/rllib/policy/policy.py", line 1518, in _initialize_loss_from_dummy_batch
    self.loss(self.model, self.dist_class, train_batch)
  File "/home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/ray/rllib/algorithms/ppo/ppo_torch_policy.py", line 141, in loss
    value_fn_out - train_batch[Postprocessing.VALUE_TARGETS], 2.0
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by ini** [comment]
Should work now for both training and visualization, as of commit 
55e47b9.

**Comment by ini** [comment]
> @ini getting similar type of issue while running visualize.py Ray version 2.9.2
> 
> (multigrid) [karuturi.t@c0900a-s29 scripts]$ python visualize.py --algo PPO --env MultiGrid-Empty-5x5-v0 --num-agents 2 --load-dir ~/blue_fujie/karuturi.t/MAgrid_repos/multigrid/scripts/saved/empty8x8/ --gif ~/blue_fujie/karuturi.t/MAgrid_repos/multigrid/scripts/saved/gif/ /home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/gymnasium/spaces/box.py:130: UserWarning: WARN: Box bound precision lowered by casting to float32 gym.logger.warn(f"Box bound precision lowered by casting to {self.dtype}") /home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/gymnasium/utils/passive_env_checker.py:164: UserWarning: WARN: The obs returned by the `reset()` method was expecting numpy array dtype to be float32, actual type: float64 logger.warn( /home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/gymnasium/utils/passive_env_checker.py:188: UserWarning: WARN: The obs returned by the `reset()` method is not within the observation space. logger.warn(f"{pre} is not within the observation space.") /home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py:483: RayDeprecationWarning: This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS="ignore::DeprecationWarning" `UnifiedLogger` will be removed in Ray 2.7. return UnifiedLogger(config, logdir, loggers=None) /home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/ray/tune/logger/unified.py:53: RayDeprecationWarning: This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS="ignore::DeprecationWarning" The `JsonLogger interface is deprecated in favor of the `ray.tune.json.JsonLoggerCallback`interface and will be removed in Ray 2.7. self._loggers.append(cls(self.config, self.logdir, self.trial)) /home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/ray/tune/logger/unified.py:53: RayDeprecationWarning: This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS="ignore::DeprecationWarning" The`CSVLogger interface is deprecated in favor of the `ray.tune.csv.CSVLoggerCallback` interface and will be removed in Ray 2.7. self._loggers.append(cls(self.config, self.logdir, self.trial)) /home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/ray/tune/logger/unified.py:53: RayDeprecationWarning: This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS="ignore::DeprecationWarning" The `TBXLogger interface is deprecated in favor of the `ray.tune.tensorboardx.TBXLoggerCallback` interface and will be removed in Ray 2.7. self._loggers.append(cls(self.config, self.logdir, self.trial)) Traceback (most recent call last): File "/blue/fujie/karuturi.t/MAgrid_repos/multigrid/scripts/visualize.py", line 137, in algorithm = config.build() File "/home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm_config.py", line 1137, in build return algo_class( File "/home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 516, in **init** super().**init**( File "/home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/ray/tune/trainable/trainable.py", line 161, in **init** self.setup(copy.deepcopy(self.config)) File "/home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/ray/rllib/algorithms/algorithm.py", line 638, in setup self.workers = WorkerSet( File "/home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/ray/rllib/evaluation/worker_set.py", line 159, in **init** self._setup( File "/home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/ray/rllib/evaluation/worker_set.py", line 249, in _setup self._local_worker = self._make_worker( File "/home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/ray/rllib/evaluation/worker_set.py", line 950, in _make_worker worker = cls( File "/home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/ray/rllib/evaluation/rollout_worker.py", line 535, in **init** self._update_policy_map(policy_dict=self.policy_dict) File "/home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1746, in _update_policy_map self._build_policy_map( File "/home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/ray/rllib/evaluation/rollout_worker.py", line 1857, in _build_policy_map new_policy = create_policy_for_framework( File "/home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/ray/rllib/utils/policy.py", line 141, in create_policy_for_framework return policy_class(observation_space, action_space, merged_config) File "/home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/ray/rllib/algorithms/ppo/ppo_torch_policy.py", line 64, in **init** self._initialize_loss_from_dummy_batch() File "/home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/ray/rllib/policy/policy.py", line 1518, in _initialize_loss_from_dummy_batch self.loss(self.model, self.dist_class, train_batch) File "/home/karuturi.t/blue_fujie/karuturi.t/conda/envs/multigrid/lib/python3.10/site-packages/ray/rllib/algorithms/ppo/ppo_torch_policy.py", line 141, in loss value_fn_out - train_batch[Postprocessing.VALUE_TARGETS], 2.0 RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

Should work now for both training and visualization, as of commit
https://github.com/ini/multigrid/commit/55e47b98b0e016fad1f745f5ad654dd2632f4c0b.
